// Authentication
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_ERROR = 'AUTH_ERROR';
export const UNAUTH_USER = 'UNAUTH_USER';
export const SET_TOKEN = 'SET_TOKEN';
export const DELETE_TOKEN = 'DELETE_TOKEN';
export const START_REFRESHING_AUTH_TOKEN = 'START_REFRESHING_AUTH_TOKEN';
export const STOP_REFRESHING_AUTH_TOKEN = 'STOP_REFRESHING_AUTH_TOKEN';
export const LOCAL_STORAGE_TOKEN_SET_FAIL = 'LOCAL_STORAGE_TOKEN_SET_FAIL';
